apiVersion: v1
kind: Secret
metadata:
  name: {{ include "slack-bot.fullname" . }}
type: Opaque
data:
  app-token: {{ .Values.slack.appToken | b64enc | quote }}
  bot-token: {{ .Values.slack.botToken | b64enc | quote }}
  bot-user-id: {{ .Values.slack.botUserID | b64enc | quote }}
  gopher-ping: {{ .Values.slack.gopherPing | b64enc | quote }}
  notification-channel-id: {{ .Values.slack.notificationChannelID | b64enc | quote }}
  workspace: {{ .Values.slack.workspace | b64enc | quote }}
